# Generated by Django 6.0 on 2025-12-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('sexe', models.CharField(max_length=100)),
                ('teams', models.ManyToManyField(related_name='persons', to='team.team')),
            ],
        ),
    ]
