# Generated by Django 6.0 on 2025-12-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='championship.championship')),
            ],
        ),
    ]
